# EDV-Coaching - Python
## Introduction to NumPy
***
This notebook covers:
- Creating and manipulating arrays
- Array operations and broadcasting
- Indexing and slicing
- Mathematical functions
- Linear algebra basics
***
# What is NumPy?

NumPy (Numerical Python) is the foundation for scientific computing in Python. It introduces a powerful N-dimensional array object and provides tools for integrating C/C++ code. <br>

Important features of NumPy are: <br>
- Efficient storage and processing of large datasets <br>
- Extensive mathematical functions for arrays <br>
- Tools for linear algebra and random numbers <br>
- Optimized performance through vectorized operations <br>
- Foundation for many other scientific Python libraries <br>

NumPy is essential for scientific calculations because it combines the speed of C with the user-friendliness of Python. <br>

## 1 Creating NumPy Arrays

NumPy's main data structure is the multidimensional array: <br>

In [ ]:
import numpy as np

# Create arrays from lists
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create special arrays
zero = np.zeros((3, 4))       # Array with zeroes
ones = np.ones((2, 3))        # Array with ones
identity = np.eye(3)           # 3x3 Identity matrix
a_range = np.arange(0, 10, 2)   # Array [0, 2, 4, 6, 8]
linear = np.linspace(0, 1, 5)   # 5 evenly distributed points

print("2D Array:")
print(arr2d)
print("\Identity matrix:")
print(identität)

2D Array:
[[1 2 3]
 [4 5 6]]

Einheitsmatrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2 Array Operations and Broadcasting

Numpy allows for efficient elementwise operations: <br>

In [ ]:
# Foundational Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

summation = a + b
product = a * b
square = a ** 2

# Broadcasting (Arrays of different dimensions)
matrix = np.array([[1, 2, 3],
                  [4, 5, 6]])
vector = np.array([10, 20, 30])

# Broadcasting adds the vector to each row of the matrix
result = matrix + vector

print("Matrix + Vector:")
print(result)

Matrix + Vektor:
[[11 22 33]
 [14 25 36]]


## 3 Indexing and Slicing

Numpy offers advanced options for indexing and slicing: <br>

In [ ]:
# Create an array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Single elements
element = arr[1, 2]     # Row 1, Column 2

# Slicing
row = arr[1, :]       # Entire second row
column = arr[:, 1]      # Entire second column
block = arr[0:2, 1:3]   # 2x2 Block from center

# Conditional Indexing
mask = arr > 6
filtered = arr[mask]  #  All elements larger than 6

print("Original Array:")
print(arr)
print("\nFiltered Block:")
print(block)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Gefilterter Block:
[[2 3]
 [6 7]]


## 4 Mathematical Functions

Numpy contains many mathematical functions: <br>

In [ ]:
# Array for Demonstrations
x = np.linspace(0, 2*np.pi, 5)

# Trigonometrical Functions
sine = np.sin(x)
cosine = np.cos(x)

# Exponential and Logarithmic
exp = np.exp(x)
log = np.log(exp)    # Natural Logarithm

# Statistics
numbers = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(numbers)
median = np.median(numbers)
std_dev = np.std(numbers)

print(f"Mean: {mean_value}")
print(f"Standard deviation: {std_dev}")

Mittelwert: 3.0
Standardabweichung: 1.4142135623730951


## 5 Linear Algebra

Numpy offers foundational functions for linear algebra: <br>

In [ ]:
# Create matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix operations
product = np.dot(A, B)      # Matrix multiplication
determinant = np.linalg.det(A)
inverse = np.linalg.inv(A)
eigenvalues = np.linalg.eigvals(A)

print("Matrix A:")
print(A)
print("\nInverse of A:")
print(inverse)
print("\nEigenvalues of A:")
print(eigenwerte)

Matrix A:
[[1 2]
 [3 4]]

Inverse von A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenwerte von A:
[-0.37228132  5.37228132]


## 6 Array Manipulation

Numpy offers various options for array manipulation: <br>

In [ ]:
# Create array
arr = np.arange(12)

# Reshape
matrix = arr.reshape(3, 4)  # 3x4 Matrix
transposed = matrix.T     # transposed

# Connect arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

vertical = np.vstack((a, b))    # Stack vertically
horizontal = np.hstack((a, b))  # Stack horizotally

print("Reshaped Matrix:")
print(matrix)
print("\nVertically stacked:")
print(vertical)

Umgeformte Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Vertikal gestapelt:
[[1 2 3]
 [4 5 6]]


## 7 Random numbers

Numpy has a module for random numbers: <br>

In [ ]:
# Uniform distribution
random_uniform = np.random.rand(3, 3)

# Normal distribution
random_normal = np.random.randn(3, 3)

# Random integers
random_int = np.random.randint(0, 10, size=(3, 3))

print("Matrix, normal distribution:")
print(random_normal)

## Conclusion:

NumPy offers: <br>
- Efficient array operations <br>
- Extensive mathematical functions <br>
- Advanced indexing capabilities <br>
- Basic linear algebra <br>
- Simple array manipulation <br>

These features form the foundation for scientific computing in Python. <br>