# Python Basics 7
## Numpy - Introduction
***
This notebook covers:
- the array class
- Creating, Indexing and Editing
***

Run the following cell to import numpy under the alias np.

In [ ]:
import numpy as np

## Introduction

`numpy` (for *Numerical Python*) is an advanced programming library for processing large multidimensional arrays and higher-order mathematical routines (linear algebra, statistics, complex mathematical functions, etc.). <br>

The object class we will mainly work with is the **`array`** class from `numpy`. <br>

These arrays correspond to N-dimensional matrices that can contain various data such as tabular data, time series, or images. <br>

The advantage of the `numpy` module lies in its ability to execute array operations very efficiently. This means that both the required **code length** and the **computation time** for these operations are significantly minimized compared to conventional `Python` syntax.

## 1 Creating a `numpy` Array

Unlike usual classes, a `numpy` array can be created with many different constructors. <br>

The argument of these constructors is usually a **`tuple`** that contains the desired matrix dimensions. This tuple is called the **Shape** of an array:

```python
# Import of the numpy module under the alias 'np'
import numpy as np

# Creating a 5x10 matrix filled with zeros
X = np.zeros(shape = (5, 10))

# Creating a 3-dimensional 3x10x10 matrix filled with ones
X = np.ones(shape = (3, 10, 10))
```

It is also possible to create an array from a **list** with the `np.array` constructor:

```python
# Creating an array from a list through List Comprehension
X = np.array([2*i for i in range(10)]) # 0, 2, 4, 6, ..., 18

# Creating an array from a list of lists
X = np.array([[1, 3, 3],
              [3, 3, 1],
              [1, 2, 0]])
```

These three constructors are just examples. We will learn about more constructors later.

## 2 Indexing a `numpy` Array

Unlike lists, a `numpy` array is multidimensional. Indexing must be done by entering the desired index **in each dimension**:

```python
# Creating a 10x10 matrix filled with ones
X = np.ones(shape = (10, 10))

# Displaying the element at index (4, 3)
print(X[4, 3])

# Assigning the value -1 to the element with index (1, 5)
X[1, 5] = -1
```

As with all other indexable Python objects, the index of an axis starts at 0. <br>

<img src="../imgs/indexation_array_en.png" style = 'height:350px'> <br>

As with lists, it is possible to index an array using **slicing**. <br>

<img src="../imgs/indexation_array_slicing_en.png" style = 'height:350px'>

It is possible to slice in **each dimension** of an array. In the following example, we will extract a **subarray** from `X` using slicing. <br>

<img src="../imgs/indexation_array_slicing2_en.png" style = 'height:350px'>

The previous examples show the indexing of a 2-dimensional array, but this type of indexing can be generalized to N-dimensional arrays. It is also possible to use **negative indexing** as with lists.

#### 2.1 Exercises:
> (a) Create and display the following diagonal block matrix using constructors and array slicing:
> 
>$$
\begin{pmatrix}
1 & 1 & 1 & 0 & 0 & 0 \\
1 & 1 & 1 & 0 & 0 & 0 \\
1 & 1 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & -1 & -1 & -1 \\
0 & 0 & 0 & -1 & -1 & -1 \\
0 & 0 & 0 & -1 & -1 & -1 \\
\end{pmatrix}
$$

In [ ]:
# Your Solution:





#### Solution:

In [ ]:
# Creating a 6x6 matrix filled with 0
X = np.zeros((6, 6), dtype='int')

# Assigning values of 1 for the upper left quarter
X[:3, :3] = 1

# Assigning values of -1 for the lower right quarter
X[3:, 3:] = -1

# Displaying the matrix
print(X)
print(type(X))

[[ 1  1  1  0  0  0]
 [ 1  1  1  0  0  0]
 [ 1  1  1  0  0  0]
 [ 0  0  0 -1 -1 -1]
 [ 0  0  0 -1 -1 -1]
 [ 0  0  0 -1 -1 -1]]
<class 'numpy.ndarray'>


#### 
> (b) Create and display the following matrix using arrays and slicing:
>  
>$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 & 5 \\
0 & 1 & 2 & 3 & 4 & 5 \\
0 & 1 & 2 & 3 & 4 & 5 \\
0 & 1 & 2 & 3 & 4 & 5 \\
0 & 1 & 2 & 3 & 4 & 5 \\
0 & 1 & 2 & 3 & 4 & 5 \\
\end{pmatrix}
$$ <br>
> You can either replace every row of a zero-matrix with `np.array([0, 1, 2, 3, 4, 5])` or assign every column its index.

In [ ]:
# Your Solution:





#### Solution:

In [ ]:
# First Solution:
X = np.zeros(shape = (6, 6))
x1 = X.astype(float)

# We replace each row with: 'np.array([0, 1, 2, 3, 4, 5])' 
for i in range (6):
    x1[i ,:] = np.array ([0, 1, 2, 3, 4, 5])

# Display:
print("First solution")
print(x1)
print("\n")

# Second Solution:
Y = np.zeros(shape = (6, 6))

# Assign each column of x its index
for i in range(6):
    Y[:, i] = i
    
# Display
print("Second solution")
print(Y)


## 3 Operations on Numpy Arrays

Most of the time you will process `numpy` arrays with real data. <br>

The value of the `numpy` module lies in its optimized **code** that enables fast calculations on large matrices. <br>

The `numpy` module contains basic mathematical functions such as:

| Function                    | Numpy Function              |
|:---------------------------:|:---------------------------:|
| $e^x$                       | `np.exp(x)`                 |
| $\mathrm{log}(x)$           | `np.log(x)`                 |
| $\mathrm{sin}(x)$           | `np.sin(x)`                 |
| $\mathrm{cos}(x)$           | `np.cos(x)`                 |
| Round to **`n`** decimal places| `np.round(x, decimals = n)` |

The complete list of mathematical operations for `numpy` can be found [here](https://numpy.org/doc/stable/reference/routines.math.html). <br>

These functions can be applied to all `numpy` arrays, regardless of their dimensions:

```python
X = np.array([i/100 for i in range(100)]) # 0, 0.01, 0.02, 0.03, ..., 0.98, 0.99

# Calculate the exponential function of x for x = 0, 0.01, 0.02, 0.03, ..., 0.98, 0.99
exp_X = np.exp(X)
```

In the next cell we will create the array:

$$
X =
\begin{pmatrix}
0.01 & 0.02 & ... & 0.98 & 0.99
\end{pmatrix}
$$

#### 3.1 Exercises:
> (a) Define a function `f` that takes an array `X` and calculates the following function **in a single line of code**: <br>
>
> $ f(x) = \mathrm{exp}(\mathrm{sin}(x) + \mathrm{cos}(x)) $ <br>
>
> (b) Display the **first 10** elements of the result **rounded to 2 decimal places** of the function `f` applied to the array `X`.

In [ ]:
# Your Solution:





#### Solution:

In [ ]:
X = np.array([i/100 for i in range(100)])

# Define function f
def f(X):
    return np.exp(np.sin(X) + np.cos(X))

# Calculate f(X)
result = f(X)

# We round the result to two decimals
rounded = np.round(result, decimals=2)

# and display the first 10 results:
print(rounded[: 10])

[2.72 2.75 2.77 2.8  2.83 2.85 2.88 2.91 2.94 2.96]


#### 
> (c) Define a function named `f_python` that applies the function from (a) to each element of X using a `for` loop. <br>
> 
> The dimensions of an array `X` can be retrieved with the **`shape`** attribute of `X`, which is a **tuple**: `shape = X.shape`. <br>
>
> For an array with **one** dimension, the number of contained elements corresponds to the **first** element of its shape: `n = X.shape[0]`. <br>

In [ ]:
# Your Solution:





#### Solution:

In [30]:
def f_python(X):
    n = X.shape[0]
    for i in range(n):
        X[i] = np.exp(np.sin(X[i]) + np.cos(X[i]))
    return X

#### 
> We will now compare the execution times of these two functions when applied to a very large array (10 million values). <br>
>
> We measure these execution times with the `time` module. To measure the execution time of a function, simply take the **difference** between **the start time of execution** and **the end time**. <br>
>
> (d) Run the next cell to compare the execution times. <br>
(Spoiler: Takes a while!)

In [ ]:
from time import time

# We create an array with 1000000 values
X = np.array([i/1e7 for i in range(int(1e7))])

time_start = time()
f(X)
time_end = time()

runtime = time_end - time_start

print (f"The calculation with numpy takes {runtime} seconds")

time_start = time()
f_python(X)
time_end = time()

runtime = time_end - time_start

print (f"The calculation with a loop takes {runtime} seconds")

As you can see, the calculation with a ```loop``` takes much longer compared to the calculation with ```numpy```. <br>
This is particularly advantageous when working with large datasets or statistical calculations, as we will see in upcoming tasks.